config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  devise_for :users

  resources :users, only: [:show] do
    member do
      get "groups", to: "users#groups"
      get "posts", to: "users#posts"
      get "liked", to: "users#liked"
    end
    resources :groups do
    end
  end

  resources :posts do
    resources :comments

    collection do
      get :recent
      get "active", to: "posts#active"
      get "popular", to: "posts#popular"
    end
    member do
      get "like", to: "posts#like"
      get "unlike", to: "posts#unlike"
      put "share", to: "posts#share"
    end
  end

  authenticated :user do
    root 'posts#index', as: 'authenticated_root'
  end

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Group < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :description, presence: true, length: { minimum: 6, maximum: 50 }

  belongs_to :user
  has_many :posts

  column_name(User)
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_group, only: [:show, :edit, :update, :destroy]
  before_action :judge_user, only: [:new, :create, :edit, :update, :destroy]

  def show
    @posts = @group.posts
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to user_group_path(current_user, @group), notice: "Successful!"
    else
      flash.now[:alert] = "some error(s) = ="
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to user_group_path(current_user, @group)
    else
      flash.now[:alert] = "some error(s) = ="
      render 'new'
    end
  end

  def destroy
    @group.destroy
    redirect_to user_path(current_user)
  end

  private

    def group_params
        params.require(:group).permit(:name, :description)
    end

    def find_group
      # @group = Group.where(id: params[:id], user_id: params[:user_id]).first
      # @group = Group.find(params[:id])
      @user = User.find(params[:user_id])
      @group = @user.groups.find(params[:id])
    end

    def judge_user
      if params[:user_id].to_i != current_user.id
        redirect_to root_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="yield_content">
  <%= render partial: 'shared/errors', locals: { item: @group } %>
  <%= render partial: 'shared/group_form', locals: { button_name: "Update Group"} %>
</div>

app/views/groups/new.html.erb
<div class="yield_content">
  <%= render partial: 'shared/errors', locals: { item: @group } %>
  <%= render partial: 'shared/group_form', locals: { button_name: "New Group"} %>
</div>

app/views/groups/show.html.erb
<div class="yield_content">
  <div class="group_show">

    <div class="group_detail">

      <h3><%= @group.name %></h3>
      <span><%= @group.description %></span>


      <% if current_user == @user %>
        <div class="group_action">
          <%= link_to edit_user_group_path(@user, @group) do %>
            <span class="fa fa-edit"></span>
          <% end %>
          <%= link_to user_group_path(@user, @group), method: :delete, data: { confirm: "Are you sure?" } do %>
            <span class="fa fa-trash-o"></span>
          <% end %>
        </div>
      <% end %>

    </div>

    <% @posts.each do |post| %>
      <%= render partial: 'shared/show_post', locals: { post: post } %>
    <% end %>

    <% if user_signed_in? && current_user == @user %>
      <div class="some_buttons">
        <%= link_to "New Post", new_post_path, class: "button button-highlight-o" %>
      </div>
    <% end %>

  </div>
</div>