config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  devise_for :users

  resources :users, only: [:show] do
    member do
      get "groups", to: "users#groups"
      get "posts", to: "users#posts"
      get "liked", to: "users#liked"
    end
    resources :groups do
    end
  end

  resources :posts do
    resources :comments

    collection do
      get :recent
      get "active", to: "posts#active"
      get "popular", to: "posts#popular"
    end
    member do
      get "like", to: "posts#like"
      get "unlike", to: "posts#unlike"
      put "share", to: "posts#share"
    end
  end

  authenticated :user do
    root 'posts#index', as: 'authenticated_root'
  end

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#  role                   :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :groups, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_create do |user|
    user.groups.create(name: 'default', description: 'The group created by system', user_id: user.id)
  end

  validates :name, presence: true, length: { minimum: 6, maximum: 20 }

  scope :groups, -> (user) { user.groups.order("created_at DESC") }
  scope :posts, -> (user) { user.posts.order("created_at DESC")}

  acts_as_voter

  def has_role?(role)
    self.role == role
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [ :show, :groups, :posts, :liked ]
  before_action :find_groups, only: [ :show, :groups ]

  def show
  end

  def groups
    render :show
  end

  def posts
    @posts = User.posts(@user).paginate(page: params[:page], per_page: 5)
    render :show
  end

  def liked
    @posts = Post.liked_by(@user).paginate(page: params[:page], per_page: 5)
    render :show
  end

  private

    def find_user
        @user = User.find(params[:id])
    end

    def find_groups
      @groups = User.groups(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="yield_content">
  <div class="user_show">

    <div class="user_detail">

      <div class="gravatar">
        <%= gravatar_for(@user) %>
      </div>

      <p class="user_name">
        <%= @user.name %>
      </p>
      <p class="user_mail">

        <%= @user.email %>
        <%= link_to edit_user_registration_path do %>
          <span class="fa fa-wrench"></span>
        <% end %>

        <% if current_user.has_role?("Admin") %>
          <br/>
          <br/>
          <%= link_to "Admin panel", admin_root_path %>
        <% end %>
      </p>
    </div>

    <div class="bar">
      <% if match_action?('show') || match_action?('groups') %>
        <%= link_to "Groups", groups_user_path, class: "selected" %>
        <%= link_to "Posts", posts_user_path %>
        <%= link_to "Liked", liked_user_path %>
      <% elsif match_action? 'posts'  %>
        <%= link_to "Groups", groups_user_path %>
        <%= link_to "Posts", posts_user_path, class: "selected" %>
        <%= link_to "Liked", liked_user_path %>
      <% elsif match_action? 'liked' %>
        <%= link_to "Groups", groups_user_path %>
        <%= link_to "Posts", posts_user_path %>
        <%= link_to "Liked", liked_user_path, class: "selected" %>
      <% end %>
    </div>

    <% if params[:action] == "show" || params[:action]  == "groups"%>
      <div class="groups">
        <% @groups.each do |group| %>
          <span><%= link_to "#{group.name}(#{group.posts.size})", user_group_path(@user, group) %></span>
        <% end %>
      </div>
    <% end %>

    <% if params[:action] == "posts" || params[:action] == "liked" %>
      <div class="posts">
        <% @posts.each do |post| %>
          <div class="post_detail">
            <div class="post_title">
              <%= link_to post.title, format_url(post.url) %>
            </div>
            <span class="post_description"><%= post.description %></span>
            <div class="post_action">
              <%= render partial: "shared/post_action", locals: { post: post } %>
            </div>
          </div>
        <% end %>

        <div class="paginate">
          <%= will_paginate @posts %>
        </div>
      </div>
    <% end %>


    <% if user_signed_in? && current_user  == @user %>
      <div class="some_buttons">
        <%= link_to "New Group", new_user_group_path(@user), class: "button button-highlight-o" %>
        <%= link_to "New Post", new_post_path, class: "button button-highlight-o" %>
      </div>
    <% end %>
  </div>
</div>