config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  devise_for :users

  resources :users, only: [:show] do
    member do
      get "groups", to: "users#groups"
      get "posts", to: "users#posts"
      get "liked", to: "users#liked"
    end
    resources :groups do
    end
  end

  resources :posts do
    resources :comments

    collection do
      get :recent
      get "active", to: "posts#active"
      get "popular", to: "posts#popular"
    end
    member do
      get "like", to: "posts#like"
      get "unlike", to: "posts#unlike"
      put "share", to: "posts#share"
    end
  end

  authenticated :user do
    root 'posts#index', as: 'authenticated_root'
  end

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_comment_form.html.erb
<div class="form">
  <%= form_for([@post, @post.comments.new]) do |f| %>
    <%= f.text_area :content, placeholder: placeholder %>
    <%= f.button "comment", class: btn_class, disabled: disabled_ans %>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if item.errors.any? %>

  <div class="error_msg">
    <p><%= pluralize(item.errors.count, "error") %></p>
    <ul>
      <% item.errors.messages.each do |msg| %>
        <% msg.last.each do |detail| %>
          <li><%= msg.first.capitalize %>: <%= detail.capitalize %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>©2015 Whatsup. All Rights Reserved.</p>
</footer>

app/views/shared/_group_form.html.erb
<div class="group_form_page">
  <div class="form">
    <%= form_for [current_user, @group] do |f| %>

      <div class="form_row">
        <%= f.text_field :name, autofocus: true, placeholder: "Name" %>
      </div>
      <div class="form_row">
        <%= f.text_area :description, placeholder: "Description" %>
      </div>

      <div class="form_row">
        <div class="action">
          <%= f.button button_name, class: "button button-highlight-o" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <%= link_to "WhatsUp", root_path, class: "logo" %>
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to current_user.name, user_path(current_user) %>
        </li>

        <!-- <li>
             <%= link_to "Account Settings", edit_user_registration_path %>
             </li>
           -->

        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/shared/_post_action.html.erb
<% if user_signed_in? %>

  <% if post.user_id == current_user.id %>

    <% if post.share %>
      <%= link_to share_post_path(post), method: :put do %>
        <span class="fa fa-ban"></span>
      <% end %>
    <% else %>
      <%= link_to share_post_path(post), method: :put do %>
        <span class="fa fa-share"></span>
      <% end %>
    <% end %>

    <%= link_to edit_post_path(post) do %>
      <span class="fa fa-pencil-square-o"></span>
    <% end %>
    <%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure?!" } do %>
      <span class="fa fa-trash-o"></span>
    <% end %>
  <% end %>

  <% if current_user.voted_up_on? post %>
    <%= link_to unlike_post_path(post) do %>
      <span class="fa fa-heart"></span>
    <% end %>
  <% else %>
    <%= link_to like_post_path(post) do %>
      <span class="fa fa-heart-o"></span>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_post_form.html.erb
<div class="post_form_page">
  <div class="form">

    <%= form_for @post do |f| %>
      <div class="form_row">
        <%= f.text_field :title, autofocus: true, placeholder: "Title" %>
      </div>

      <div class="form_row">
        <%= f.text_field :url, placeholder: "URL" %>
      </div>

      <div class="form_row">
        <%= f.label :share %>
        <%= f.check_box :share%>
      </div>

      <div class="form_row">
        <%= f.label :select_group %>
        <%= f.select(:group_id, options_for_select(@group_options, @selected_id)) %>
        <%= link_to "New Group", new_user_group_path(current_user) %>
      </div>


      <div class="form_row">
        <%= f.text_area :description, placeholder: "Description: (Maximum: 50 characters)" %>
      </div>

      <div class="form_row">
        <div class="action">
          <%= f.button button_name, class: "button button-highlight-o" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_show_post.html.erb
<div class="each_post">

  <div class="like_size">
    <span class="fa fa-sort"></span>
    <%= post.get_likes.size %>
  </div>

  <div class="post_detail">
    <div class="post_title">
      <%= link_to post.title, format_url(post.url) %>
    </div>
    <span class="post_description"><%= post.description %></span>
  </div>

  <div class="post_author">
    <%= link_to "#{ post.user.name }", user_path(post.user) %>
  </div>
  <div class="post_action">

    <%= render partial: "shared/post_action", locals: { post: post } %>

    <%= link_to post_path(post) do %>
      <span class="fa fa-comment-o"></span>
      <span class="comment_size"><%= post.comments_count %></span>
    <% end %>

  </div>
</div>