config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'static_pages/home'

  devise_for :users

  resources :users, only: [:show] do
    member do
      get "groups", to: "users#groups"
      get "posts", to: "users#posts"
      get "liked", to: "users#liked"
    end
    resources :groups do
    end
  end

  resources :posts do
    resources :comments

    collection do
      get :recent
      get "active", to: "posts#active"
      get "popular", to: "posts#popular"
    end
    member do
      get "like", to: "posts#like"
      get "unlike", to: "posts#unlike"
      put "share", to: "posts#share"
    end
  end

  authenticated :user do
    root 'posts#index', as: 'authenticated_root'
  end

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id             :integer          not null, primary key
#  title          :string
#  url            :string
#  description    :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  share          :boolean          default(FALSE)
#  group_id       :integer
#  comments_count :integer          default(0)
#  likes_count    :integer          default(0)
#

class Post < ApplicationRecord
  URL_REGEX = /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z/

  validates :title, presence: true, length: {
              minimum: 5, maximum: 30,
              too_long: "%{count} characters is the maximum allowed",
              too_short: "%{count} characters is the minimum allowed"
            }

  validates :url, presence: true, format: {
              with: URL_REGEX,
              message: "Invalid URL format!"
            }

  validates :description, presence: true, length: {
              maximum: 50,
              too_long: "%{count} characters is the maximum allowed"
            }

  belongs_to :user
  belongs_to :group
  has_many :comments, dependent: :destroy

  scope :recent, -> { where(share: true).order("created_at DESC") }
  scope :active, -> { where("share = ? and comments_count >= ?", true, 3) }
  scope :popular, -> { order(likes_count: :DESC, created_at: :DESC) }

  scope :all_recent, -> (n) { order("created_at DESC").limit(n) }

  scope :liked_by, -> (user) {
    # array to ActiveRecord::Relation
    posts_id = find_each.select { |post| user.voted_for? post }.map(&:id)
    where(id: posts_id)
  }

  self.per_page = 10

  acts_as_votable

  column_name(User)
  column_name(Group)

  # def self.column_name(model)
  #   model_format = model.to_s.downcase
  #   method_name = model_format + '_name'
  #   define_method(method_name) do
  #     column = model_format + '_id'
  #     model.find(self.send(column.to_sym)).name
  #   end
  # end


  # def user_name
  #   User.find(self.user_id).name
  # end

  # def group_name
  #   Group.find(self.group_id).name
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy, :like, :unlike, :share, :is_share?, :group_setting]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :judge_user, only: [:edit, :update, :destroy, :share]


  def index
    @posts = Post.recent.paginate(page: params[:page])
  end

  def show
    # for error msg
    @comment = @post.comments.new
  end

  def new
    @post = current_user.posts.new
    group_setting
  end

  def create
    @post = current_user.posts.new(post_params)
    group_setting

    if @post.save
      redirect_to @post, notice: "Create successfully~~"
    else
      flash.now[:alert] = "Something wrong here!!"
      render 'new'
    end
  end

  def edit
    group_setting
  end

  def update
    group_setting
    if @post.update(post_params)
      redirect_to @post, notice: "Update successfully~~"
    else
      flash.now[:alert] = "Something wrong here!!"
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def like
    @post.liked_by current_user
    @post.update_attribute(:likes_count, @post.get_likes.size)
    redirect_to :back
  end

  def unlike
    @post.unliked_by current_user
    @post.update_attribute(:likes_count, @post.get_likes.size)
    redirect_to :back
  end

  def share
    is_share? ? @post.update(share: false) : @post.update(share: true)
    redirect_to :back
  end

  def recent
    @posts = Post.recent.paginate(page: params[:page])
    render action: :index
  end

  def active
    @posts = Post.active.paginate(page: params[:page])
    render action: :index
  end

  def popular
    @posts = Post.popular.paginate(page: params[:page])
    render action: :index
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :share, :group_id, :description)
    end

    def judge_user
      find_post
      if @post.user_id != current_user.id
        redirect_to root_path
      end
    end

    def is_share?
      @post.share
    end

    def set_group_options
      @group_options = current_user.groups.all.map.with_index do |group, group_id|
        [group.name.to_sym, group.id]
      end
    end

    def get_selected_id
      @selected_id = @post.group_id || 1
    end

    def group_setting
      set_group_options
      get_selected_id
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="yield_content">

  <%= render partial: 'shared/errors', locals: { item: @post } %>

  <%= render partial: 'shared/post_form', locals: { button_name: "Update Post" } %>

  <div class="some_links">
    <%= link_to "back", post_path%>
  </div>

</div>

app/views/posts/index.html.erb
<div class="yield_content">

  <div class="bar">
    <% if match_action? 'recent' %>
      <%= link_to "Popular", popular_posts_path %>
      <%= link_to "Active", active_posts_path %>
      <%= link_to "Recent", recent_posts_path, class: "selected" %>
    <% elsif match_action? 'active'  %>
      <%= link_to "Popular", popular_posts_path %>
      <%= link_to "Active", active_posts_path, class: "selected" %>
      <%= link_to "Recent", recent_posts_path %>
    <% elsif match_action? 'popular'  %>
      <%= link_to "Popular", popular_posts_path, class: "selected" %>
      <%= link_to "Active", active_posts_path %>
      <%= link_to "Recent", recent_posts_path %>
    <% else %>
      <%= link_to "Popular", popular_posts_path %>
      <%= link_to "Active", active_posts_path %>
      <%= link_to "Recent", recent_posts_path %>
    <% end %>
  </div>

  <div class="posts_content">
    <% @posts.each do |post|%>
      <%= render partial: 'shared/show_post', locals: { post: post } %>
    <% end %>
  </div>

  <div class="paginate">
    <%= will_paginate @posts %>
  </div>

  <% if user_signed_in? %>
    <div class="some_buttons">
      <%= link_to "New Post", new_post_path, class: "button button-highlight-o" %>
    </div>
  <% end %>


</div>

app/views/posts/new.html.erb
<div class="yield_content">
  <%= render partial: 'shared/errors', locals: { item: @post } %>
  <%= render partial: 'shared/post_form', locals: { button_name: "New Post" } %>
</div>

app/views/posts/show.html.erb
<div class="yield_content">
<div class="post_show">
  <div class="like_size">
    <span class="fa fa-sort"></span>
    <%= @post.get_likes.size %>
  </div>

  <div class="post_detail">
    <div class="post_title">
      <%= link_to @post.title, format_url(@post.url) %>
    </div>


    <div class="post_author">
      <% if @post.created_at == @post.updated_at %>
        <span>Created by</span>
        <%= link_to "#{ @post.user.name }", user_path(@post.user) %>
        <span>on <%= @post.created_at.strftime("%B %d, %Y") %></span>
      <% else %>
        <span>Updated by</span>
        <%= link_to "#{ @post.user.name }", user_path(@post.user) %>
        <span>on <%= @post.updated_at.strftime("%B %d, %Y") %></span>
      <% end %>
    </div>

    <div class="post_action">
      <%= render partial: "shared/post_action", locals: { post: @post } %>
    </div>

    <span class="post_description"><%= @post.description %></span>

  </div>
</div>

<div class="comment_area">

  <%= render partial: 'shared/errors', locals: { item: @comment } %>

  <% if user_signed_in? %>
    <%= render partial: "shared/comment_form", locals: { placeholder: "Any comments?", disabled_ans: false, btn_class: "button button-highlight-o" } %>
  <% else %>
    <%= render partial: "shared/comment_form", locals: { placeholder: "Please login or sign up for leaving comment(s)", disabled_ans: true, btn_class: "button button-disable" } %>
  <% end %>

  <div class="post_comments">
    <% comments_group = find_comments_group(@post) %>

    <% comments_group.each do |user, comment| %>
      <div class="comment">

        <div class="comment_user">
          <div class="gravatar">
            <%= gravatar_for(user) %>
          </div>
        </div>

        <div class="comment_content">
          <div class="status">
            <%= link_to user.name, user_path(user) %>
            commented on
            <%= comment.created_at.strftime("%B %d, %Y") %>
          </div>
          <div class="content"><%= comment.content %></div>
        </div>

      </div>
    <% end %>
  </div>
</div>
</div>